#include "hal_data.h"

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
typedef struct{
	uint8_t irq_channel;
	void (*init)(void);
	void (*handler)(void);
}Button_Object;


typedef struct{
		bsp_io_port_pin_t pin;
		void (*on)(bsp_io_port_pin_t pin);
		void (*off)(bsp_io_port_pin_t pin);	
		}LED_TypeDef;
void LED_On(bsp_io_port_pin_t pin){
		R_IOPORT_PinWrite(&g_ioport_ctrl,pin,BSP_IO_LEVEL_HIGH);
		}
void LED_Off(bsp_io_port_pin_t pin){
		R_IOPORT_PinWrite(&g_ioport_ctrl,pin,BSP_IO_LEVEL_LOW);
		}
void LED_Toggle(void){
static bsp_io_level_t state = BSP_IO_LEVEL_LOW;
	state = (state == BSP_IO_LEVEL_LOW)? BSP_IO_LEVEL_HIGH:BSP_IO_LEVEL_LOW;
	R_IOPORT_PinWrite(&g_ioport_ctrl,BSP_IO_PORT_04_PIN_00,state);
}
void button_callback(external_irq_callback_args_t *p_grgs){
	(void)p_grgs;
	LED_Toggle();

}
void hal_entry(void)
{
    /* TODO: add your own code here */
	/*
    LED_TypeDef blue_led={
			.pin = BSP_IO_PORT_04_PIN_00,
			.on = LED_On,
			.off = LED_Off
    };
	*/
	R_ICU_ExternalIrqOpen(&g_external_irq6_ctrl,&g_external_irq6_cfg);
	R_ICU_ExternalIrqEnable(&g_external_irq6_ctrl);
		while (1){
/*
		blue_led.on(blue_led.pin);
		R_BSP_SoftwareDelay(500,BSP_DELAY_UNITS_MILLISECONDS);
		blue_led.off(blue_led.pin);
		R_BSP_SoftwareDelay(500,BSP_DELAY_UNITS_MILLISECONDS);
*/	
			R_BSP_SoftwareDelay(1,BSP_DELAY_UNITS_SECONDS);
			}
	
	
		
	
    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif


#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
